apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todoapp
              image: busyboxplus:curl
              command:
                - /bin/sh
                - -c
                - curl -s http://todoapp-service.mateapp.svc.cluster.local/api/health || echo "Healthcheck failed"
              resources:
                  requests:
                    cpu: "100m"
                    memory: "128Mi"
                  limits:
                    cpu: "200m"
                    memory: "256Mi"
          restartPolicy: OnFailure
