apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp-service
  template:
    metadata:
      labels:
        app: todoapp-service
    spec:
      containers:
        - name: todoapp-service
          image: busyboxplus:curl
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008
